name: Check for AC
on:
  workflow_dispatch:
  schedule:
    #- cron: '0-30/2 0 * * 1-5'
    - cron: '15 1 * * 1-5'
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CONFIG: ${{ secrets.CONFIG }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Worker code
        run: node index.js
