name: Check for AC
on:
  workflow_dispatch:
  schedule:
    #- cron: '0-30/2 0 * * 1-5'
    - cron: '0 0 * * 1-5'
    - cron: '2 0 * * 1-5'
    - cron: '4 0 * * 1-5'
    - cron: '6 0 * * 1-5'
    - cron: '8 0 * * 1-5'
    - cron: '10 0 * * 1-5'
    - cron: '12 0 * * 1-5'
    - cron: '14 0 * * 1-5'
    - cron: '16 0 * * 1-5'
    - cron: '18 0 * * 1-5'
    - cron: '20 0 * * 1-5'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Worker code
        run: node index.js
